### ISSUE TITLE
possible to use deoplete instead of asyncomplete.vim for autocompletion?

### ISSUE THREAD

**Issue by indraniel** [alaviss/nim.nvim#10]
Is it possible for this vim plugin to use [deoplete.nvim](https://github.com/Shougo/deoplete.nvim) instead of [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) for the autocomplete functionality?  if so, what would need to be done to enable that?

**Comment by alaviss** [comment]
It's not possible. `deoplete.nvim` completion sources have to be written in Python, and I don't know how well can python interface with neovim's async.

It's also possible to support deoplete by introducing omnicomplete support, but that'd requires https://github.com/neovim/neovim/pull/10382 (so async operations can be blocking), which is not in any neovim release yet.

**Comment by indraniel** [comment]
I see.  So using [deoplete-vim-lsp](https://github.com/lighttiger2505/deoplete-vim-lsp) would not be useful here?

**Comment by alaviss** [comment]
You can use them to run auto completion also, but please note that `nimlsp` is yet another `nimsuggest` and will be started per-file, which will eat your RAM really quickly.

Unless you have to use deoplete, I'd recommend switching to something that supports completion source written in vimscript so that you could use the `nimsuggest` instance spawned by this plugin directly. So far I found `prabirshrestha/asyncomplete.vim` and `neoclide/coc.nvim` hosts this capability.

**Comment by indraniel** [comment]
Gotcha!  Thanks again for the additional explanations!
