### ISSUE TITLE
Syntax highlighting in macros

### ISSUE THREAD

**Issue by vitreo12** [alaviss/nim.nvim#13]
Hi,

I just noticed that syntax highlighting doesn't work quite well in macros, especially when nesting them. Like so:

![smth](https://cdn1.imggmi.com/uploads/2019/8/30/13e6dd99e556f62e7da729123d09adc6-full.png)

**Comment by alaviss** [comment]
This is to be expected. In such context those nodes are `untyped`, so nimsuggest doesn't attempt to do anything more than constructing an AST tree for the macro.
 
If the macro generate code based on those AST nodes, then you'll see the highlighting.

Sent with  FairEmail [https://email.faircode.eu/]  , an open source, privacy friendly email app for Android

Sat Aug 31 00:50:16 GMT+07:00 2019 Francesco Cameli <notifications@github.com>:

**Comment by vitreo12** [comment]
Is there a way, then, to have syntax highlighted just by the text code, instead of going through nimsuggest (while still retaining all of its auto-complete features) ? Something like VSCode's extension. This would be very useful for my case, which is of a Domain Specific Language through macros.

**Comment by alaviss** [comment]
> Is there a way, then, to have syntax highlighted just by the text code, instead of going through nimsuggest.

Yes, this is possible and is used by almost all Nim plugin out there. For this plugin I avoided that completely, because text-based highlighting can and will errornously highlight code in certain context. Instead `nimsuggest` is employed due to it's correctness.

I believe that if you generate code based on the nodes passed to the macro, it will retains the line info which can be used by `nimsuggest` to properly highlight the code. Macros like `gara.match` does this and their DSLs can be properly highlighted by nimsuggest.
